### ISSUE TITLE
[REQUEST FEATURE] Ajouter possibilité de modifier un commentaire

### ISSUE THREAD

**Issue by thoms27** [LyonParapente/EventOrganizer#2]
Salut,

L'idée de pouvoir modifier un commentaire, c'est surtout pour corriger des fautes le plus souvent.
Avec les téléphones c'est vite fait de se tromper.
Quant à la rétention des informations... est ce utile pour notre utilisation ?
Ou alors pouvoir modifier un commentaire tant que quelqu'un n'a pas répondu
Je sais pas à voir ^^ C'est pas pour te donner du boulot, juste pour voir si on peut le faire évoluer en fonction des demandes

++

**Comment by TiTi** [comment]
de mondifier? :-p
la feature te sera bien utile c'est sûr ^^

pas mal l'idée du "tant que quelqu'un n'a pas répondu" ; on peut aussi envisager un déclenchement de l'email un peu plus tard pour avoir les micro-corrections

**Comment by thoms27** [comment]
Tu as modifié mon message ? je ne vois pas l'erreur. Ou alors notifier d'un changement, mais ca risque de spammer

**Comment by thoms27** [comment]
ah oui le sujet ...
