### ISSUE TITLE
Ajout d'une feature d'export des événements vers différents formats

### ISSUE THREAD

**Issue by pilebones** [LyonParapente/EventOrganizer#3]
Permettre d'exporter un événement vers un autre calendrier (Google calendar, icalendar) pour le consulter facilement sur mobile après validation de la participation.

**Comment by TiTi** [comment]
Intéressant, à voir ou mettre le lien dans la GUI et la faisabilité technique.
Cela dit, l'idée est plutôt que les pilotes utilisent le calendrier plutôt que leur calendrier, notamment pour voir les commentaires.
(ce qui va de pair avec les notifs)
Mais ça peut-être utile pour un événement lointain

**Comment by romuald101** [comment]
Pour un seul événement je suppose, donc c'est plutôt pour gérer son agenda
perso, et avoir un rappel. Dans ce cas il faudrait inclure dans cet
événement un lien vers l'événement en question de Kikivol pour juste
retrouver rapidement la pages avec les commentaires.
Ca ne remplace pas kikivol mais ca le complète.
C'est ce que j'en comprends.

Le lun. 16 nov. 2020 à 20:09, Thibault ROHMER <notifications@github.com> a
écrit :

**Comment by pilebones** [comment]
C'est exactement l'idée @romuald101  👍 juste centraliser dans son agenda les évènements auquels l'utilisateur participe avec un lien vers kikivol sans pour autant chercher à le remplacer.
Le bouton pourrait apparaitre si participation confirmée ?

**Comment by romuald101** [comment]
On voit les hommes organisés ! 😉

Le mar. 1 déc. 2020 à 15:59, Mickael FRANC <notifications@github.com> a
écrit :

**Comment by TiTi** [comment]
N'hésitez pas à faire une PR.

---
> Le bouton pourrait apparaitre si participation confirmée ?

toutafé. tout est possible, tout est réalisable.

**Comment by TiTi** [comment]
Effectué : abe26a4fe061f3c4eda971885aa4aaf425f687df

![image](https://user-images.githubusercontent.com/137691/101413067-ed021380-38e3-11eb-8bd5-e17112554efc.png)

**Comment by pilebones** [comment]
Yes je viens de pouvoir tester à l'instant sur le dernier event que tu as créé.

Après téléchargement du `.ics`, je peux l'importer nickel sur Google Agenda. J'ai le nom, la description, le lien vers kikivol, la localisation, etc.... de l'event. Bref, ça marche au top sur Android. Bien joué. 

Petite idée d'amélioration, j'ai entendu parlé de l'URL scheme `calshow://` qui permettrait p-e d'ouvrir automatiquement l'application associé sur mobile: 
https://en.it1352.com/article/cdf479efe198463c93c15a7eb199df56.html
Si l'implémentation est galère selon les devices de l'utilisateur, laisse tomber.
